name: gltf
version: 2.0.0-dev
description: Library for loading and validating glTF 2.0 assets
author: The Khronos Group Inc.
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.3'
  path:
  quiver: '^0.25.0'
  vector_math: '^2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

environment:
  sdk: '>=1.24.0'

executables:
  gltf_validator:

transformers:
 - dart_to_js_script_rewriter